version: '2'
services:
  remotespark:
#    image: simonkowallik/remotespark:latest
    build:
      context: .
      args:
        SPARK_VERSION: "latest"
        EMBED: "true"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./logs:/usr/local/bin/SparkGateway/logs
#      - ./data:/usr/local/bin/SparkGateway/data
#      - ./gateway.conf:/usr/local/bin/SparkGateway/gateway.conf:ro
